#ifndef __DFHWBUCH__
#define __DFHWBUCH__

#include <cics_rvb.h>

/* ----------------------------------------------------------------- */
/* This copybook defines the constants which are used by             */
/* the Converter Programs.                                           */
/* ----------------------------------------------------------------- */

#define URP_DECODE           COBHALF(1)
#define URP_ENCODE           COBHALF(2)

#define URP_OK               COBWORD(0)
#define URP_EXCEPTION        COBWORD(4)
#define URP_INVALID          COBWORD(8)
#define URP_DISASTER         COBWORD(12)
#define URP_OK_LOOP          COBWORD(16)

#define WBRA_TYPE_HTTP       1
#define WBRA_TYPE_NON_HTTP   2
#define WBRA_UNESCAPE_REQUIRED 3
#define WBRA_UNESCAPE_NOT_REQUIRED 4

#define WBEP_BLIO_GREATER_THAN_32K_RESPONSE COBWORD(1)
#define WBEP_COMMAREA_NO_CONTENT COBWORD(2)
#define WBEP_DFHWBBLI_DOCUMENT_NOT_FOUND COBWORD(3)
#define WBEP_DFHWBBLI_CODEPAGE_NOT_FOUND COBWORD(4)
#define WBEP_DFHWBBLI_API_ERROR COBWORD(5)
#define WBEP_DFHWBBLI_LINK_FAILED_TERMERR COBWORD(6)
#define WBEP_DFHWBBLI_LINK_FAILED_INVREQ COBWORD(7)
#define WBEP_DFHWBBLI_LINK_FAILED_LENGERR COBWORD(8)
#define WBEP_DFHWBBLI_LINK_FAILED_PGMIDERR COBWORD(9)
#define WBEP_DFHWBBLI_LINK_FAILED_SYSIDERR COBWORD(10)
#define WBEP_DFHWBBLI_LINK_FAILED_ROLLEDBACK COBWORD(11)
#define WBEP_DFHWBBLI_LINK_FAILED_NOTAUTH COBWORD(12)
#define WBEP_DFHWBBLI_LINK_FAILED COBWORD(13)
#define WBEP_INVALID_DECODE_PARAMETER_LIST COBWORD(14)
#define WBEP_DECODE_ERROR    COBWORD(15)
#define WBEP_INVALID_ENCODE_PARAMETER_LIST COBWORD(16)
#define WBEP_ENCODE_ERROR    COBWORD(17)
#define WBEP_SAVE_CERTIFICATE_FAILED COBWORD(18)
#define WBEP_DFHWBBLI_ABEND_HANDLER_INVOKED COBWORD(19)
#define WBEP_INVALID_ATTACH  COBWORD(20)
#define WBEP_RECEIVE_ERROR   COBWORD(21)
#define WBEP_ANALYZER_LINK_ERROR COBWORD(22)
#define WBEP_DFHWBXN_CODEPAGE_ERROR COBWORD(23)
#define WBEP_NO_ANALYZER_SPECIFIED COBWORD(24)
#define WBEP_RECEIVE_STORAGE_ERROR COBWORD(25)
#define WBEP_HEADER_LENGTH_ERROR COBWORD(26)
#define WBEP_DFHWBXN_LOGIC_ERROR COBWORD(27)
#define WBEP_LINK_DFHWBBLI_FAILED COBWORD(28)
#define WBEP_ANALYZER_ERROR  COBWORD(29)
#define WBEP_ANALYZER_DATALENGTH_ERROR COBWORD(30)
#define WBEP_NOT_AUTHORIZED_TO_START_ALIAS COBWORD(31)
#define WBEP_DFHWBBLI_BAD_PREVIOUS_WEB_SEND COBWORD(32)
#define WBEP_BAD_COMMAREA_RESPONSE COBWORD(33)
#define WBEP_ALIAS_TASK_PURGED COBWORD(34)
#define WBEP_SECURITY_UNKNOWN_ESM_RESP COBWORD(35)
#define WBEP_SECURITY_ESM_NOT_RESPONDING COBWORD(36)
#define WBEP_SECURITY_APPLICATION_NOTAUTH COBWORD(37)
#define WBEP_SECURITY_USERID_REVOKED COBWORD(38)
#define WBEP_SECURITY_SECLABEL_CHECK_FAILED COBWORD(39)
#define WBEP_SECURITY_GROUP_ACCESS_REVOKED COBWORD(40)
#define WBEP_SECURITY_INVALID_USERID COBWORD(41)
#define WBEP_ATTACH_LOGIC_ERROR COBWORD(42)
#define WBEP_USER_NOT_AUTHORISED COBWORD(43)
#define WBEP_CLIENT_AUTHENTICATION_ERROR COBWORD(44)
#define WBEP_ANALYZER_ABENDED COBWORD(45)
#define WBEP_ABNORMAL_TERMINATION COBWORD(46)

#define URP_SECURITY_FAILURE COBWORD(1)
#define URP_CORRUPT_CLIENT_DATA COBWORD(2)
#define URP_RECEIVE_OUTSTANDING COBWORD(3)

#define URP_RESOURCE_TOO_SHORT 1
#define URP_FIRST_SLASH_MISSING 2
#define URP_CONV_NAME_INVALID 4
#define URP_TRAN_NAME_INVALID 5
#define URP_SERV_NAME_INVALID 6
#define URP_USER_TOKEN_INVALID 7
#define URP_SERVER_NAME_MISSING 8

#define DECODE_EYECATCHER_INIT ">decode "
#define ENCODE_EYECATCHER_INIT ">encode "
#define ANALYZE_EYECATCHER_INIT ">analyze"
#define DFHWBUN_EYECATCHER_INIT ">dfhwbun"

#define CNV_HTTP_HEADER_KEY  "DFHWBHH "
#define CNV_USER_DATA_KEY    "DFHWBUD "

#define DFHWBUN_CURRENT_VERSION 2

/* VERSIONS */
#define UNIKIX_CWBI_VERSION_1 '\0'
#define UNIKIX_CWBI_VERSION_2 '0'

/* VOLATILITY */
#define UNIKIX_CAN_BE_REPLACED     '0'
#define UNIKIX_CANNOT_BE_REPLACED  '1'
#endif
